# model parameters
model:
  layers: [2, 30, 20, 1]

# dataset params
dataset:
  base_num_samples: [20,100]
  noise: 0.0
  shuffle: True
  val_split: .2
  batch_size: 28

## augmentation params
augmentation:
  type: Gaussian
  noise: 0.05
  num_of_iterations: 10

# training params
train:
  loss_func: binary_cross_entropy_with_logits
  optimizer: SGD
  lr: 0.05
  epochs: 30
