_target_: src.models.mlp_module.MLPLitModule

# model architecture
layers: [2, 30, 20, 1]
task: "binary"
num_classes: 2

# optimizer
optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0

# learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5 # reduce lr by half
  patience: 10
