# create decision boundary
decision_boundary:
  _target_: src.callbacks.wandb_callbacks.LogDecisionBoundary
  dirpath: ${paths.output_dir} # path where to store decision boundary plot default is under the experiment logs

watch_model:
  _target_: src.callbacks.wandb_callbacks.WatchModel
  log: "all" # log gradients, parameter histogram and model topology
  log_freq: 100
  log_graph: True

LogWeightBiasDistribution:
  _target_: src.callbacks.wandb_callbacks.LogWeightBiasDistribution
  dirpath: ${paths.output_dir} # path where to store weight and bias distribution plots, default is under the experiment logs

LogSklearnDatasetPlots:
  _target_: src.callbacks.wandb_callbacks.LogSklearnDatasetPlots
  dirpath: ${paths.output_dir} # path where to store dataset plots, default is under the experiment logs

AddToConfigEffectiveTrainSize:
  _target_: src.callbacks.wandb_callbacks.AddToConfigEffectiveTrainSize

upload_ckpts_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
  ckpt_dir: "checkpoints/"
  upload_best_only: True
