_target_: src.datamodules.sklearn_datamodule.create_sklearn_datamodule
dataset:
  _target_: sklearn.datasets.make_moons
  n_samples: 20
  shuffle: True

# The augmentation function to use.
# The effective training size becomes n_samples * (n_augmentations + 1)
data_aug:
  _partial_: True
  _target_: src.data_augmentations.gaussian.augment_data
  noise: 0.05 # the noise added to the augmented samples
  n_augmentations: 0  # number of augmentation iteration.


